name: Release Binaries

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Backend Dependecy Install
        run: go mod download
        working-directory: ./

      - name: Log in to Mono Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Push to Mono Registry
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            kintsdev/test-kube:latest

